-- Add Budget Tracking and Reports Analytics to global feature settings
INSERT INTO public.global_feature_settings (
  feature_key,
  feature_name,
  enabled,
  display_name,
  description,
  show_as_upcoming,
  parent_feature_key,
  category,
  sort_order,
  requires_subscription,
  show_in_sidebar,
  sidebar_order,
  sidebar_path
) VALUES 
(
  'budget_tracking',
  'Budget Tracking',
  true,
  'Budget Tracking',
  'Track project budgets, expenses, and financial allocations',
  false,
  NULL,
  'finance',
  70,
  NULL,
  true,
  3,
  '/budget'
),
(
  'expense_categories',
  'Expense Categories',
  true,
  'Expense Categories',
  'Manage expense classification categories',
  false,
  'budget_tracking',
  'finance',
  71,
  NULL,
  false,
  NULL,
  NULL
),
(
  'invoice_management',
  'Invoice Management',
  true,
  'Invoice Management',
  'Create and track invoices for income management',
  false,
  'budget_tracking',
  'finance',
  72,
  NULL,
  false,
  NULL,
  NULL
),
(
  'reports_analytics',
  'Reports & Analytics',
  true,
  'Reports & Analytics',
  'Comprehensive project performance and financial reports',
  false,
  NULL,
  'reports',
  80,
  NULL,
  true,
  4,
  '/reports'
),
(
  'reports_overview',
  'Reports Overview',
  true,
  'Reports Overview',
  'High-level project performance overview',
  false,
  'reports_analytics',
  'reports',
  81,
  NULL,
  false,
  NULL,
  NULL
),
(
  'reports_financial',
  'Financial Reports',
  true,
  'Financial Reports',
  'Detailed financial analysis and budget reports',
  false,
  'reports_analytics',
  'reports',
  82,
  NULL,
  false,
  NULL,
  NULL
),
(
  'reports_trends',
  'Trend Analysis',
  true,
  'Trend Analysis',
  'Historical trends and forecasting analytics',
  false,
  'reports_analytics',
  'reports',
  83,
  NULL,
  false,
  NULL,
  NULL
)
ON CONFLICT (feature_key) DO UPDATE SET
  feature_name = EXCLUDED.feature_name,
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  parent_feature_key = EXCLUDED.parent_feature_key;