// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkvhihqkfeqqkqhgthsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rdmhpaHFrZmVxcWtxaGd0aHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3Nzk5OTYsImV4cCI6MjA4NDM1NTk5Nn0.7mQTx8ZoyjV9k8tpTH5zNzC3S4dnxZkyplElkvqUYYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});